### ISSUE TITLE
Icon Tribute

### ISSUE THREAD

**Issue by rappen** [mikefactorial/MikeFactorial.XTB.Plugins.UniversalSearch#1]
Looks like you left some icons from my sample code... 😉

![image](https://user-images.githubusercontent.com/2572253/49475215-40fd2d80-f7dc-11e8-93e4-b8568587f91d.png)

![image](https://user-images.githubusercontent.com/2572253/49475232-4f4b4980-f7dc-11e8-91e0-dc1a86f78eec.png)

**Comment by mikefactorial** [comment]
Aww man. I guess I owe you some royalties. What's 10% of $0.00? I'll update it 👍

**Comment by mikefactorial** [comment]
I've updated the icons. Thought about using your face but didn't want to risk further litigation. Thanks Jonas!

**Comment by mikefactorial** [comment]
Updated in 1.0.7 release
