### ISSUE TITLE
Include option set labels

### ISSUE THREAD

**Issue by akaskela** [mikefactorial/MikeFactorial.XTB.Plugins.UniversalSearch#2]
It'd be sweet if you included global and non-global option sets in the search. I'm working with a tool that maps from picklists to a form and having trouble tracking down the source.

**Comment by mikefactorial** [comment]
Yeah, I have to look at this. I'm excluding fields that have certain Metadata attributes that probably exclude the picklistattribute(name). Thanks Aiden

**Comment by mikefactorial** [comment]
I know I can retrieve those attributes, but I think they throw an exception if you try to search them because they are child attributes. I'd have to use the metadata to determine what value to search based on the text which might be slow. Any thoughts on making that more performant?

**Comment by akaskela** [comment]
You'd have to go through the metadata but make it an option that you have to opt in to for a given search so you don't have to wait unless you want the metadata searched.

**Comment by mikefactorial** [comment]
Yeah, had to do the same thing for the case sensitive search since it slows it down to do the calculations after retrieving the results. Probably wouldn't add that much more overhead though

**Comment by mikefactorial** [comment]
This has been resolved in version 1.1.0.

**Comment by mikefactorial** [comment]
There’s an option to search option set and / or lookup display values now with a warning that searches may be slower as a result
