### ISSUE TITLE
It keeps asking to install 1.1.1 version

### ISSUE THREAD

**Issue by awesomegithubusername** [mikefactorial/MikeFactorial.XTB.Plugins.UniversalSearch#3]
Hello,

I'm not sure if this is an XrmToolBox issue or a plugin issue. The plugins store keeps proposing an update (version 1.1.1) even after installing it and restarting the program.

XrmToolBox version: 1.2019.6.33

**Comment by JamesStuder** [comment]
Same on my end as well.

**Comment by mikefactorial** [comment]
Thanks for the heads up guys. It was a publishing issue. The version number of the assembly didn't match the Nuget version. I just updated the Nuget Package and assembly version to 1.1.2. No longer keeps asking.
